{
 "title": "ilyab de Status Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Decision Engine Status",
   "type": "stat",
   "description": "Decision Engine Status - Can be UP or DOWN",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(de_status{job=\"decisionengine-dev-ilyab\"} OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Number of DE Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(de_workers_total{instance=\"fermicloud857.fnal.gov:8000\"})"
    }
   ]
  },
  {
   "title": "Start Channel Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_start_channel_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "Start Channel Duration Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_start_channel_duration_seconds_sum{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/de_client_start_channel_duration_seconds_count{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}\r\n"
    }
   ]
  },
  {
   "title": "Status Query Duration ",
   "type": "timeseries",
   "description": "Duration for running de-client --status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_status_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) ",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50,\r\nsum(rate(de_client_status_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Status Duration Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "de_client_status_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_status_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "Print Product Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_print_product_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) \r\n"
    }
   ]
  },
  {
   "title": "Print Product Duration Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_print_product_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_print_product_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"} )\r\n"
    }
   ]
  },
  {
   "title": "Metrics Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_metrics_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Metrics Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "de_client_metrics_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_metrics_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"} > 0)"
    }
   ]
  },
  {
   "title": "De Client Ping Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_ping_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Ping Duration Second Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_ping_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_ping_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "De Client Show Config Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_show_config_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Show Config Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_show_config_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_show_config_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "De Client Show De Config Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_show_de_config_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Show DE Config Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_show_de_config_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_show_de_config_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Print Products Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\r\nsum(rate(de_client_print_products_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Print Products Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_print_products_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_print_products_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "De Client Queue Status Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_queue_status_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Queue Status Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_queue_status_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_queue_status_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Product Dependencies Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_product_dependencies_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Product Dependencies Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_product_dependencies_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_product_dependencies_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Stop Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_stop_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Stop Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_stop_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_stop_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Create Channel Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_create_channel_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Create Channel Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_create_channel_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_create_channel_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Start Channels Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_start_channels_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Start Channels Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_start_channels_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_start_channels_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Stop Channels Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_stop_channels_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Stop Channels Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_stop_channels_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_stop_channels_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Reaper Start Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_reaper_start_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_reaper_start_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Reaper Start Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_reaper_start_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Reaper Stop Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_reaper_stop_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Reaper Stop Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_reaper_stop_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_reaper_stop_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "DE Client Reaper Status Duration Seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\nsum(rate(de_client_reaper_status_duration_seconds_bucket{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) by (le)) "
    }
   ]
  },
  {
   "title": "DE Client Reaper Status Duration Seconds Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_reaper_status_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_reaper_status_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})"
    }
   ]
  },
  {
   "title": "All Metrics Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "de_client_start_channel_duration_seconds_sum{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/de_client_start_channel_duration_seconds_count{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}\r\n",
     "legendFormat": "Start Channel"
    },
    {
     "expr": "de_client_status_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_status_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Status"
    },
    {
     "expr": "de_client_print_product_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_print_product_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"} > 0)",
     "legendFormat": "Print Product"
    },
    {
     "expr": "de_client_metrics_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_metrics_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Metrics"
    },
    {
     "expr": "de_client_ping_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_ping_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Ping"
    },
    {
     "expr": "de_client_show_config_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_show_config_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Show Config"
    },
    {
     "expr": "de_client_show_de_config_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_show_de_config_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Show DE Config"
    },
    {
     "expr": "de_client_queue_status_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_queue_status_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Queue Status"
    },
    {
     "expr": "de_client_product_dependencies_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_product_dependencies_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Product Dependencies"
    },
    {
     "expr": "de_client_stop_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_stop_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Stop"
    },
    {
     "expr": "de_client_create_channel_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_create_channel_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Create Channel"
    },
    {
     "expr": "de_client_start_channels_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_start_channels_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Start Channels"
    },
    {
     "expr": "de_client_stop_channels_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_stop_channels_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Stop Channels"
    },
    {
     "expr": "de_client_reaper_start_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_reaper_start_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Reaper Start"
    },
    {
     "expr": "de_client_reaper_stop_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_reaper_stop_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Reaper Stop"
    },
    {
     "expr": "de_client_reaper_status_duration_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}/(de_client_reaper_status_duration_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"})",
     "legendFormat": "Reaper Status"
    }
   ]
  }
 ]
}